# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83aea58d438bdc0e390dca480ef6295735bba21e4e6cb094e778d1a00aec9352ac06b6367d4e41ff7d41b3d18a0d1688cbc7c951d9334a21321e60de0a12935f

test:
  secret_key_base: a5c680d164d810af4777d692cd0a42c7fc4a1ca8353090c0f6e3774faf72f93394f4ec6cd0b1d2bf3141af0dd46efac65879c760048535d9d765e6b7d2964a14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
